server:
  port: 80
spring:
  application:
    name: cloud-consumer-hystrix-order

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/

#设置hystrix的默认超时时间
hystrix:
  metrics:
    polling-interval-ms: 6000

#调用@FeignClient的服务降级方法，一个方法对应一个降级处理
feign:
  hystrix:
    enabled: true

ribbon:
  # 建立连接所用时间
  ReadTimeout: 8000
  # 建立连接后读取可用资源所用的时间
  ConnectTimeout: 8000

